spring:
  datasource:
    url: jdbc:h2:mem:~/test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  front:
    origin: http://localhost:3000

security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000
