spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
server:
  front:
    origin: http://localhost:3000
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000